// automatically generated by the FlatBuffers compiler, do not modify

package dedp.DistanceOracles.FlatBuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Wsp extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Wsp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long code() { return bb.getLong(bb_pos + 0); }
  public short level() { return bb.getShort(bb_pos + 8); }
  public float distance() { return bb.getFloat(bb_pos + 12); }

  public static int createWsp(FlatBufferBuilder builder, long code, short level, float distance) {
    builder.prep(8, 16);
    builder.putFloat(distance);
    builder.pad(2);
    builder.putShort(level);
    builder.putLong(code);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Wsp get(int j) { return get(new Wsp(), j); }
    public Wsp get(Wsp obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

